# Build section: Defines the build command and the directory to publish
[build]
  # The command to build the app (ensure you have a build script defined in package.json)
  command = "npm run build"

  # The directory that contains the built app files
  publish = "dist"

# Optional: Set environment variables if necessary for your build
[build.environment]
  NODE_VERSION = "20"  # Use the correct Node version as per your setup (replace 16 with 20)

# Optional: Handle client-side routing for SPAs (Single Page Apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
