[build]
  command = "npm run build"
  publish = "dist"

# Optional: Set environment variables if needed
[build.environment]
  NODE_VERSION = "16"  # Update to the version you need

# Optional: Handle client-side routing (for SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
